/**
 * Color enums generated by Style Dictionary (`pnpm run build:tokens` in this package).
 * Do not edit files under `./generated/` by hand.
 */
export { WuiColorName } from "./generated/WuiColorName.enum";
export { WuiColorValue } from "./generated/WuiColorValue.enum";
export { WuiColorAlias } from "./generated/WuiColorAlias.enum";
